# Generated by Django 4.1.1 on 2022-09-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classnowapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
    ]
