# Generated by Django 4.1.1 on 2022-09-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classnowapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_est',
            old_name='username_est',
            new_name='user',
        ),
    ]
