# Generated by Django 4.1.1 on 2022-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnowapp', '0002_rename_username_est_account_est_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_est',
            name='username_est',
            field=models.CharField(max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
