# Generated by Django 4.1.1 on 2022-09-22 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classnowapp', '0002_alter_user_celular_alter_user_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100, verbose_name='Tema')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
