# Generated by Django 4.1.1 on 2022-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnowapp', '0003_alter_user_est_username_est'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id_profesores', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('celular', models.CharField(max_length=30, verbose_name='Celular')),
                ('edad', models.CharField(max_length=10, verbose_name='Edad')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('genero', models.CharField(max_length=5, verbose_name='Genero')),
                ('password', models.CharField(max_length=250, verbose_name='Contraseña')),
                ('rol_usuario', models.CharField(max_length=20, verbose_name='Rol Usuario')),
            ],
        ),
    ]
